packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  bun: true
catalog:
  "@effect/language-service": ^0.86.2
  "@effect/platform-node": 4.0.0-rc.111
  "@effect/sql-mssql": 4.0.0-rc.111
  "@effect/sql-mysql2": 4.0.0-rc.111
  "@effect/sql-pg": 4.0.0-rc.111
  "@effect/sql-sqlite-bun": 4.0.0-rc.111
  "@effect/sql-sqlite-node": 4.0.0-rc.111
  "@effect/vitest": 4.0.0-rc.111
  effect: 4.0.0-rc.111
