packages:
  - "apps/*"
  - "examples/*"
  - "packages/*"
allowBuilds:
  "@swc/core": true
  bun: true
  cbor-extract: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
catalog:
  "@effect/language-service": ^0.86.2
  "@effect/platform-node": 4.0.0-rc.113
  "@effect/sql-mssql": 4.0.0-rc.113
  "@effect/sql-mysql2": 4.0.0-rc.113
  "@effect/sql-pg": 4.0.0-rc.113
  "@effect/sql-sqlite-bun": 4.0.0-rc.113
  "@effect/sql-sqlite-node": 4.0.0-rc.113
  "@effect/vitest": 4.0.0-rc.113
  effect: 4.0.0-rc.113
